language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

script:
  - composer update $COMPOSER_PREFER
  - vendor/bin/phpcs --standard=phpcs.xml classes tests
  - vendor/bin/atoum --test-ext
